# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.srcs/sources_1/bd/buffer_rams/ip/buffer_rams_blk_mem_gen_0_3/buffer_rams_blk_mem_gen_0_3.xci
# IP: The module: 'buffer_rams_blk_mem_gen_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.gen/sources_1/bd/buffer_rams/ip/buffer_rams_blk_mem_gen_0_3/buffer_rams_blk_mem_gen_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_rams_blk_mem_gen_0_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.srcs/sources_1/bd/buffer_rams/ip/buffer_rams_blk_mem_gen_0_3/buffer_rams_blk_mem_gen_0_3.xci
# IP: The module: 'buffer_rams_blk_mem_gen_0_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.gen/sources_1/bd/buffer_rams/ip/buffer_rams_blk_mem_gen_0_3/buffer_rams_blk_mem_gen_0_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'buffer_rams_blk_mem_gen_0_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
