# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.srcs/sources_1/bd/Rams_512/ip/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0.xci
# IP: The module: 'Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.gen/sources_1/bd/Rams_512/ip/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.srcs/sources_1/bd/Rams_512/ip/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0.xci
# IP: The module: 'Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.gen/sources_1/bd/Rams_512/ip/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
