# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sprite_mem/sprite_mem.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sprite_mem || ORIG_REF_NAME==sprite_mem} -quiet] -quiet

# IP: bd/sprite_mem/ip/sprite_mem_blk_mem_gen_0_0/sprite_mem_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sprite_mem_blk_mem_gen_0_0 || ORIG_REF_NAME==sprite_mem_blk_mem_gen_0_0} -quiet] -quiet

# Block Designs: bd/frame_buffer/frame_buffer.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==frame_buffer || ORIG_REF_NAME==frame_buffer} -quiet] -quiet

# IP: bd/frame_buffer/ip/frame_buffer_blk_mem_gen_0_0/frame_buffer_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==frame_buffer_blk_mem_gen_0_0 || ORIG_REF_NAME==frame_buffer_blk_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.gen/sources_1/bd/sprite_mem/sprite_mem_ooc.xdc

# XDC: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.gen/sources_1/bd/frame_buffer/frame_buffer_ooc.xdc
