# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/Rams_512/Rams_512.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rams_512 || ORIG_REF_NAME==Rams_512} -quiet] -quiet

# IP: bd/Rams_512/ip/Rams_512_blk_mem_gen_0_0/Rams_512_blk_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rams_512_blk_mem_gen_0_0 || ORIG_REF_NAME==Rams_512_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Rams_512/ip/Rams_512_blk_mem_gen_0_1/Rams_512_blk_mem_gen_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rams_512_blk_mem_gen_0_1 || ORIG_REF_NAME==Rams_512_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/Rams_512/ip/Rams_512_blk_mem_gen_0_2/Rams_512_blk_mem_gen_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rams_512_blk_mem_gen_0_2 || ORIG_REF_NAME==Rams_512_blk_mem_gen_0_2} -quiet] -quiet

# IP: bd/Rams_512/ip/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0/Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0 || ORIG_REF_NAME==Rams_512_UPPER_PREVIOUS_512_mem_gen_0_0} -quiet] -quiet

# XDC: c:/Users/jabilio.000/Documents/git/Sprite_Machine/VDP/VDP.gen/sources_1/bd/Rams_512/Rams_512_ooc.xdc
